Allow overlapping activities
OpenC3/cosmos pull request #1383
Opened 2024-07-05 21:24 UTC by jmthomas

2024-07-05 21:40 UTC, ryanmelt requested changes
I think the time validation should be optional with an argument provided to create/update .  It can default to don't validate, but sometimes I think it would a nice option to guarantee no overlaps.

2024-07-07 16:18 UTC, ryanmelt commented
Overlap option looks great.   The other thing I'm worried about is ordering if we have multiple items in the same second.  Is there anyway we can enforce ordering?

2024-07-07 16:25 UTC, jmthomas commented
Should we just allow sub-second start time and force the user to ensure ordering?

2024-07-07 16:28 UTC, ryanmelt commented
I think that would work.  If two items have the exact same time, that implies that the order shouldn't matter.

2024-07-09 01:47 UTC, ryanmelt commented on openc3/lib/openc3/models/activity_model.rb
> +      array = Store.zrevrangebyscore(@primary_key, "(#{@stop}", @start - MAX_DURATION)
What is going on with the weird parentheses in the quoted string here?

2024-07-09 01:47 UTC, ryanmelt commented on openc3/lib/openc3/models/activity_model.rb
> +      array = Store.zrevrangebyscore(@primary_key, "(#{@stop}", @start - MAX_DURATION)
Nevermind - Nice comment!

2024-07-09 01:48 UTC, ryanmelt approved these changes

2024-07-09 03:02 UTC, merged