Signal widget
OpenC3/cosmos pull request #1386
Opened 2024-07-07 22:11 UTC by jmthomas

closes #1377

2024-07-07 22:12 UTC, jmthomas commented
<img width="341" alt="Screenshot 2024-07-07 at 4 00 02 PM" src="https://github.com/OpenC3/cosmos/assets/176403/33e4725e-a475-4525-bca8-53eb2643a7f7">

2024-07-09 01:40 UTC, ryanmelt requested changes

2024-07-09 01:40 UTC, ryanmelt commented on openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST/screens/rollup.txt
> +  SIGNAL INST HEALTH_STATUS TEMP1
Screens should use ```<%= target_name %>```

2024-07-09 01:40 UTC, ryanmelt commented on openc3-cosmos-init/plugins/packages/openc3-cosmos-demo/targets/INST2/screens/rollup.txt
> +    SETTING TLM INST2 HEALTH_STATUS TEMP1
Screens should use ```<%= target_name %>```

2024-07-09 14:32 UTC, merged