Fix python accessors and packet restore_defaults
OpenC3/cosmos pull request #1399
Opened 2024-07-12 19:28 UTC by jmthomas

closes #1376

2024-07-12 21:37 UTC, ryanmelt requested changes

2024-07-12 23:02 UTC, jmthomas commented on openc3/python/openc3/accessors/json_accessor.py
> +        except (UnicodeDecodeError, AttributeError):
Attempt at duck-typing the input so we could use bytes or bytearray ... I think we need bytearray (mutable) so I'll revert back.

2024-07-12 23:22 UTC, jmthomas commented on openc3/python/openc3/packets/packet.py
> +            buffer = self._buffer
This was the main fix to packet.py

2024-07-12 23:23 UTC, jmthomas commented on openc3/python/openc3/packets/packet_config.py
> +                self.current_packet.template = bytearray(params[0], "ascii")
Template must be a bytearray

2024-07-13 01:59 UTC, ryanmelt approved these changes

2024-07-13 02:30 UTC, merged