Correct spelling errors
OpenC3/cosmos pull request #1496
Opened 2024-08-23 23:02 UTC by jmthomas

2024-08-23 23:10 UTC, jmthomas commented on openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/Dialogs/AskDialog.vue
> +</style>
Actual bug

2024-08-23 23:10 UTC, jmthomas commented on openc3/lib/openc3/utilities/metric.rb
> +      @mutex.synchronize do
Actual bug

2024-08-26 16:15 UTC, ryanmelt requested changes
That's a lot of spelling errors!
One spelling error still "discret" is French.
Also please add a spell checker to our CI/CD pipeline so that these don't start building up again.

2024-08-26 16:15 UTC, ryanmelt commented on README.md
> +   - Script Runner also allows you to break your operational or test procedures down into discret test cases that each complete with either SUCCESS or FAILURE. After running, a script report is autom
should be discrete

2024-08-26 20:16 UTC, ryanmelt approved these changes

2024-08-26 20:46 UTC, merged