Add wait / pause time to state
OpenC3/cosmos pull request #1616
Opened 2024-10-04 00:24 UTC by jmthomas

closes #1457

2024-10-04 00:25 UTC, jmthomas commented
<img width="1172" alt="Screenshot 2024-10-03 at 6 24 44 PM" src="https://github.com/user-attachments/assets/bce1858e-a067-4d97-8ca3-fb9fc4fb9879">
<img width="1172" alt="Screenshot 2024-10-03 at 6 25 01 PM" src="https://github.com/user-attachments/assets/eeea0dc9-9f1a-4486-94c1-24533f0081ae">

2024-10-12 04:58 UTC, ryanmelt requested changes

2024-10-12 04:58 UTC, ryanmelt commented on openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue
> +        this.waitingTime += 1
This won't be very accurate over long durations.  Should save start of waiting. And then calculate as now - starttime.

2024-10-13 02:42 UTC, ryanmelt approved these changes

2024-10-13 02:42 UTC, merged