Add DATE and TIME widgets
OpenC3/cosmos pull request #1636
Opened 2024-10-18 19:43 UTC by jmthomas

closes #1634

2024-10-19 19:16 UTC, jmthomas commented
<img width="704" alt="Screenshot 2024-10-19 at 1 15 51 PM" src="https://github.com/user-attachments/assets/d1a0356c-bf61-4ffe-b9b0-98300352c124">
<img width="868" alt="Screenshot 2024-10-19 at 1 16 16 PM" src="https://github.com/user-attachments/assets/41c764c6-9c27-447e-8b42-bec44d6de60b">

2024-10-24 03:26 UTC, ryanmelt reviewed
Expected to see use of timeZone.  Is that missing?

2024-10-24 03:27 UTC, ryanmelt requested changes
Expected to see use of TimeZone

2024-10-26 17:11 UTC, ryanmelt approved these changes

2024-10-26 17:11 UTC, merged