Display range on limits bar hover
OpenC3/cosmos pull request #1648
Opened 2024-10-21 17:20 UTC by jmthomas

closes #1288

2024-10-21 17:20 UTC, jmthomas commented
<img width="396" alt="Screenshot 2024-10-21 at 11 18 32 AM" src="https://github.com/user-attachments/assets/62aedc12-4b9a-4260-87ad-d3d2297aeb1e">
<img width="396" alt="Screenshot 2024-10-21 at 11 18 36 AM" src="https://github.com/user-attachments/assets/78aa1c38-79ee-4f56-9037-b99ba8c5bf94">

2024-10-24 02:27 UTC, ryanmelt requested changes

2024-10-24 02:27 UTC, ryanmelt commented on openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/LimitsbarWidget.vue
> +      return this.limitsSettings[this.selectedLimitsSet]
This would be better with RL/value YL/value, etc.  See Details Dialog.

2024-10-24 21:54 UTC, jmthomas commented
<img width="541" alt="Screenshot 2024-10-24 at 3 53 07 PM" src="https://github.com/user-attachments/assets/c270f65d-5d85-423f-88e1-741ab4960193">

2024-10-26 17:10 UTC, ryanmelt approved these changes

2024-10-26 17:10 UTC, merged