Cmd history docs
OpenC3/cosmos pull request #1685
Opened 2024-11-01 14:50 UTC by jmthomas

2024-11-01 14:51 UTC, jmthomas commented
Roadmap formatting to have better checkboxes:
<img width="858" alt="Screenshot 2024-11-01 at 8 51 23 AM" src="https://github.com/user-attachments/assets/4834d568-0aa9-4413-8a4f-2efc42a5dbed">

2024-11-06 20:59 UTC, jmthomas reviewed
@ryanmelt  ready for review

2024-11-06 20:59 UTC, jmthomas commented on docs.openc3.com/docs/configuration/_command.md
> +  myEmoji: 📡
I always hated the icons that went on those top level collection pages. I also updated the description throughout.
<img width="982" alt="Screenshot 2024-11-06 at 1 49 01 PM" src="https://github.com/user-attachments/assets/3e9a5c77-66b9-4b25-a9e8-fbbf3738ff0f">

2024-11-06 20:59 UTC, jmthomas commented on docs.openc3.com/docs/getting-started/gettingstarted.md
> +   Target BOB successfully generated!
I switched the default example to python

2024-11-06 20:59 UTC, jmthomas commented on docs.openc3.com/docs/getting-started/installation.md
> +If you're on linux (recommended for production), we recommend installing Docker using your native package manager. Note: Red Hat users should read the [Podman](podman) documentation. If you're on Win
Added a note to clarify using native Docker on linux and only Docker Desktop on Mac and Windows

2024-11-06 20:59 UTC, jmthomas commented on docs.openc3.com/docs/meta/licenses.md
> +   We have several international customers and are not subject to ITAR export controls. We are export controlled under the EAR via ECCN 5D002c1. We have a detailed writeup explaining this justificati
@ryanmelt  These were taken straight from customer email requests. Please review for accuracy.

2024-11-06 20:59 UTC, jmthomas commented on docs.openc3.com/docs/tools/cmd-tlm-server.md
> +
Just a blurb here about Critical Command Mode because it shows up on the Scopes page. I'm not sure where else we should document this.

2024-11-06 20:59 UTC, jmthomas commented on docs.openc3.com/src/theme/DocCard/index.js
> +    item?.customProps?.myEmoji ?? (isInternalUrl(item.href) ? "📄️" : "🔗");
This is the only line that I changed after 'swizzeling` the DocCard. I followed this example: https://github.com/facebook/docusaurus/discussions/10476

```
npm run swizzle @docusaurus/theme-classic DocCard -- --eject
```

2024-11-08 04:09 UTC, ryanmelt requested changes

2024-11-08 22:54 UTC, ryanmelt approved these changes

2024-11-08 22:57 UTC, merged