BucketExplorer view files and breadcrumb paths
OpenC3/cosmos pull request #1696
Opened 2024-11-09 19:01 UTC by jmthomas

closes #1264
closes #1679 
closes #1680

2024-11-10 23:44 UTC, ryanmelt requested changes

2024-11-10 23:44 UTC, ryanmelt commented on openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-bucketexplorer/src/tools/BucketExplorer/BucketExplorer.vue
> +            v-if="item.icon === 'mdi-file' && !isBinary(item.name)"
Would be better to have isText instead of isBinary.  That way you know a file is viewable, rather than just excluding 4 extensions.

2024-11-13 03:24 UTC, jmthomas commented
<img width="1066" alt="Screenshot 2024-11-12 at 8 24 29 PM" src="https://github.com/user-attachments/assets/c3d393ce-3346-4198-be96-75429574f1b7">

2024-11-14 18:14 UTC, ryanmelt approved these changes

2024-11-14 18:46 UTC, merged