Script apis
OpenC3/cosmos pull request #1803
Opened 2024-12-30 22:55 UTC by jmthomas

2025-01-27 18:52 UTC, ryan-pratt approved these changes

2025-01-27 18:52 UTC, ryan-pratt commented on openc3-cosmos-script-runner-api/app/models/running_script.rb
> +    OpenC3::StoreQueued.set("running-script:#{@id}", @details.as_json(:allow_nan => true).to_json(:allow_nan => true))
Is the `as_json` needed here?

2025-01-27 18:52 UTC, ryan-pratt commented on openc3/lib/openc3/script/script_runner.rb
> +      response = $script_runner_api_server.request('get', endpoint, cope: scope)
typo?

2025-01-27 18:53 UTC, jmthomas commented on openc3/lib/openc3/script/script_runner.rb
> +      response = $script_runner_api_server.request('get', endpoint, cope: scope)
Nice catch!

2025-01-27 18:56 UTC, jmthomas commented on openc3-cosmos-script-runner-api/app/models/running_script.rb
> +    OpenC3::StoreQueued.set("running-script:#{@id}", @details.as_json(:allow_nan => true).to_json(:allow_nan => true))
I think so ... I was following the pattern in `spawn`. `as_json` converts the symbol keys to strings and then `to_json` converts the entire thing to a json string. Not sure if `as_json` is explicitly required but it doesn't hurt.

2025-01-28 01:58 UTC, ryanmelt requested changes

2025-01-28 01:58 UTC, ryanmelt commented on openc3-cosmos-cmd-tlm-api/app/controllers/activity_controller.rb
> +      puts "activities index limit:#{limit}"
remove debug code.

2025-01-28 01:58 UTC, ryanmelt commented on openc3-cosmos-script-runner-api/app/controllers/running_script_controller.rb
> +      ActionCable.server.broadcast("cmd-running-script-channel:#{params[:id]}", "stop")
I think this is missing script_api: at the beginning of the stream name...?

2025-01-28 02:41 UTC, ryanmelt approved these changes

2025-01-28 17:22 UTC, merged