Implement microservice & conversion generator
OpenC3/cosmos pull request #502
Opened 2023-02-21 00:44 UTC by jmthomas

closes #390

2023-02-21 00:45 UTC, jmthomas commented
@ryanmelt Not finished but I wanted to get your take on it. I think it makes sense to use the template system I already had so we can rename things and make it nicer for the end user. I need to find a good way to test these.

2023-02-22 14:53 UTC, ryanmelt requested changes
Also refactor to make base plugin and be able to add targets.

2023-02-22 14:53 UTC, ryanmelt commented on .github/workflows/cli.yml
> +      #     ../openc3.sh cliroot validate openc3-cosmos-pw-test-1.0.0.gem
why is this commented out?

2023-02-22 14:53 UTC, ryanmelt commented on openc3/templates/microservice/microservices/TEMPLATE/template.rb
> +        end
Run should increment @count

2023-02-23 02:17 UTC, ryanmelt approved these changes

2023-02-23 13:33 UTC, merged