Add Key Concepts page
OpenC3/cosmos pull request #950
Opened 2023-11-24 16:19 UTC by jmthomas

I'll need to regenerate the site before merge but check this out and let me know what you think. This is the result of a few recent discussions we've had about confusion about the architecture and things we're doing.

2023-12-07 15:13 UTC, jmthomas commented
closes #961

2023-12-09 22:43 UTC, ryanmelt requested changes
Overall good new content!
I don't really like differentiating images and containers.  I think that just confuses users.  I would just describe each of the containers, and not differentiate.

2023-12-09 22:43 UTC, ryanmelt commented on docs.openc3.com/docs/getting-started/key_concepts.md
> +The main COSMOS [repo](https://github.com/OpenC3/cosmos) contains all the source code used to build and run COSMOS. However, users (not developers) of COSMOS should use the COSMOS [project](https://g
Additionally it contains user modifiable config files for both Redis and Traefik.

2023-12-09 22:43 UTC, ryanmelt commented on docs.openc3.com/docs/getting-started/key_concepts.md
> +| [openc3-operator](https://github.com/OpenC3/cosmos/blob/main/openc3-operator/Dockerfile)                                 | Sets up the base image to run microservice_operator.rb
Inconsistent - does not mention builds on openc3-base

2023-12-09 22:43 UTC, ryanmelt commented on docs.openc3.com/docs/getting-started/key_concepts.md
> +
Also includes nfs in Kubernetes.

2023-12-09 22:43 UTC, ryanmelt commented on docs.openc3.com/docs/getting-started/key_concepts.md
> +The image list for [Enterprise COSMOS](https://openc3.com/enterprise) consists of the following:
containers.

2023-12-11 21:53 UTC, merged